cmd: python ./train.py
image: adrialopez/modem-drs:4.1.0 # adrialopez/modem-drs:4.1.0, adrialopez/modem-drs:3.2.0 # nicklashansen/hierarchy:0.1.0
conda_env: maniskill3 # maniskill3, bigym
user: adrialopezescoriza
repo: modem
branch: main # maniskill3 # speedups
cpu: 6
mem: 90 # Online training static 1M buffer
# mem: 50 # Online training dynamic 1M buffer
disk: 100
gpu: 1
namespace: ucsd-haosulab
pvc: alopez-fast-vol
allowed_gpus:
  # - NVIDIA-GeForce-RTX-2080-Ti # 11GB
  - NVIDIA-GeForce-RTX-4090 # 24GB
  - NVIDIA-GeForce-RTX-3090 # 24GB
  # - NVIDIA-TITAN-RTX # 24GB
  # - NVIDIA-RTX-A5000 # 24GB
  # - Quadro-RTX-6000 # 24GB
  #- Tesla-V100-SXM2-32GB # 32GB
  # - NVIDIA-A40 # 48GB
  # - NVIDIA-RTX-A6000 # 48GB
  # - Quadro-RTX-8000 # 48GB
  # - NVIDIA-A100-SXM4-80GB # 80GB
  # - NVIDIA-A100-80GB-PCIe # 80GB
