apiVersion: v1
kind: Pod
metadata:
  name: alopez-login  # use your own initials
spec:
  containers:
  - name: alopez-login
    image: adrialopez/modem-drs:0.0.0  # name of your image
    workingDir: /root  # name of your volume
    imagePullPolicy: Always
    args: ["sleep", "infinity"]
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /alopez-fast-vol  # name of your volume
        name: alopez-fast-vol  # name of your volume
    resources:
      requests:
        cpu: 2
        memory: 12Gi
        nvidia.com/gpu: 1
      limits:
        cpu: 2
        memory: 12Gi
        nvidia.com/gpu: 1
  restartPolicy: Never
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: alopez-fast-vol  # name of your volume
      persistentVolumeClaim:
        claimName: alopez-fast-vol  # name of your volume
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k8s-gpu-3.ucr.edu
                      - gpn-fiona.usd.edu